### ISSUE TITLE
Cast Image doesn't show in Staff Sync View

### ISSUE THREAD

**Issue by rbanker** [UNICEF-Youth-Section/Locast-Android#13]
There is a placeholder in the Staff Sync view for the cast image, but the associated image doesn't display.  I would say that the placeholder could actually be removed in the sync screen.

**Comment by xxv** [comment]
We've found that having the image there helps make the app feel more "alive" by exposing the content. Showing the thumbnails shouldn't be too hard-- there's already code in other activities to do it, it'll just take a bit of copying.

**Comment by rbanker** [comment]
For this release, we'll leave as is.  Good update for next release.
