### ISSUE TITLE
Cast Sync Screen: Edit Cast Doesn't Display Image

### ISSUE THREAD

**Issue by rbanker** [UNICEF-Youth-Section/Locast-Android#14]
The long-press on a cast in the Staff Sync Screen displays a view/edit/delete context menu.  The Cast Edit doesn't display the image in the placeholder.

**Comment by xxv** [comment]
The Edit Cast view is the same as the new cast view (or should be).  Using the ImageCache for this activity (as mentioned in #11) should fix this.
