### ISSUE TITLE
Cast Sync: View Context Option doesn't display cast

### ISSUE THREAD

**Issue by rbanker** [UNICEF-Youth-Section/Locast-Android#15]
The long-press on a cast in the Staff Sync Screen displays a view/edit/delete context menu. The Cast View option presents a spinner that never dismisses and the cast information is never displayed.  I would say that View could actually be removed for now and just allow Edit and Delete.

**Comment by xxv** [comment]
What activity has the infinite spinner?

**Comment by rbanker** [comment]
This is resolved (not sure what changed, but we're good).
