### ISSUE TITLE
Cast Sync: Media is no longer uploaded with Cast Sync

### ISSUE THREAD

**Issue by rbanker** [UNICEF-Youth-Section/Locast-Android#16]
Something appears to have happened in the last few days where the Cast Media is no longer uploaded with the cast.  The file name appears to be saved to the DB (viewable in Django admin), but the media does not display in the web ui.

**Comment by rbanker** [comment]
This looks to be working again...  I'm getting media uploaded with my casts.  Any idea what changed?

**Comment by rbanker** [comment]
OK -- so this is really hit or miss and I'm not seeing the pattern yet.  Today, media is not uploading.  Still working on repro steps.

**Comment by xxv** [comment]
There are some deep sync issues that I'm working on resolving which should most likely fix this problem. Try not to spend too much time on reproducing it as a large amount of sync code will be fixed soon.
