### ISSUE TITLE
Cast Create: Itinerary Not Saved with Cast

### ISSUE THREAD

**Issue by rbanker** [UNICEF-Youth-Section/Locast-Android#17]
New Casts don't seem to be saved with the Map/Itinerary data.  The Web UI show an empty 'Mapped On' field and the casts can only be viewed by the creating user.  Viewing the list of casts for the itinerary does not display the new cast, so I assume the data is not being saved.

**Comment by xxv** [comment]
There's a fix for this in the works. The sync framework reported the wrong canonical URI for casts that are in itineraries.
