### ISSUE TITLE
Itinerary/Map List Displays Empty Media Place Holders

### ISSUE THREAD

**Issue by rbanker** [UNICEF-Youth-Section/Locast-Android#18]
The initial Itinerary/Map view displays an empty media place holder.  I'm not currently sure what media would be chosen for the display (most recent cast? random?)  Does the Itinerary/Map list need a media placeholder?

**Comment by xxv** [comment]
Itineraries/Maps are allowed to have a picture that's chosen in the web UI. This could be used to our advantage to help "brand" Maps.

**Comment by rbanker** [comment]
Gotcha.  Closing.
