### ISSUE TITLE
Capture Media Date/Time Taken for Display in Web UI

### ISSUE THREAD

**Issue by rbanker** [UNICEF-Youth-Section/Locast-Android#19]
It would be nice to capture the date/time of individual media.  Possibility: is this stored in the EXIF info of the media?

**Comment by xxv** [comment]
Currently the client extracts location information from the photo (using the DB, not EXIF). We'd need to load in an EXIF library to be able to extract EXIF info (I believe).

**Comment by rbanker** [comment]
This has been coded and pushed, but not tested.  Still requires addition of server-side data storage and display
