### ISSUE TITLE
Cast Add: Multiple Photos Still Captured although not displayed in Client

### ISSUE THREAD

**Issue by rbanker** [UNICEF-Youth-Section/Locast-Android#20]
Taking a new photo in a cast after one has already been taken does not remove previous photo.  It is simply added to the list of media (at least this is what appears to be happening in the DB).  Depending on the situation, this could either be a bug or a feature :-)  It still allows the user to take multiple photos that could then be removed if necessary from the Web UI.  

Doesn't seem high priority to me, but in a future release, making it clear that new photos are additive to the Cast would be good.

**Comment by xxv** [comment]
If the UI only displays one photo, then it should replace any existing media. Otherwise, it should show an icon for each media item on the CastEdit screen.
