### ISSUE TITLE
Cast Add: Need to disable landscape mode

### ISSUE THREAD

**Issue by rbanker** [UNICEF-Youth-Section/Locast-Android#21]
Currently, the New Cast screen will rotate into landcape mode if the phone is reoriented.  This isn't a useful orientation for the Cast Add activity.

**Comment by rbanker** [comment]
Updated AndroidManifest to force portrait mode.

**Comment by xxv** [comment]
That really depends on the device. If it's a device with a hardware keyboard that slides out in landscape mode, then it's extremely useful.

**Comment by rbanker** [comment]
Restored landscape view with ScrollView.
