### ISSUE TITLE
Sync Activity usability: need empty view

### ISSUE THREAD

**Issue by xxv** [UNICEF-Youth-Section/Locast-Android#22]
In the Sync activity, currently, if there are no casts pending upload, an empty list (no items or indication that there could be items) is shown. There should be a text notice so that people are reassured that the sync finished successfully.

**Comment by rbanker** [comment]
Ary: Could you take a look at this?

**Comment by asterite** [comment]
Sure

**Comment by asterite** [comment]
https://github.com/UNICEF-Youth-Section/Locast-Android/commit/d7426f007065b67ebb57001d74e162bdb8072f31
