### ISSUE TITLE
Sync Activity usability: casts disappear before media is sync'd

### ISSUE THREAD

**Issue by xxv** [UNICEF-Youth-Section/Locast-Android#23]
There's a usability bug with the way that sync happens now. Currently, cast metadata sync and media sync are handled separately. The idea behind the separation was to allow for the app to be more usable (browsing, etc.) while a big upload/download went on. I think this is still useful, but there is no coordination between the two states - media doesn't know when its cast is sync'd and vice versa.

Perhaps there could be a "media dirty" bit in the cast that gets set when the state of the media items are known to be inconsistent with the server.

**Comment by rbanker** [comment]
Ary: Could you look at this as well?

**Comment by asterite** [comment]
If the metadata and media sync are separated, and no state is stored in the cast to know which one were synced, how can I know when to remove it from the list? I think the sync needs to be solved first. Also, I can't see how this can work correctly without knowing what fields were synced... why the sync is not done in a single step?

**Comment by rbanker** [comment]
Steve:

FYI from Ary.  Any comments?

On Tue, Jan 24, 2012 at 11:33 AM, Ary Borenszweig <
reply@reply.github.com

> wrote:
> 
> If the metadata and media sync are separated, and no state is stored in
> the cast to know which one were synced, how can I know when to remove it
> from the list? I think the sync needs to be solved first. Also, I can't see
> how this can work correctly without knowing what fields were synced... why
> the sync is not done in a single step?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/UNICEF-Youth-Section/Locast-Android/issues/23#issuecomment-3635308

## 

Rob Banker
rbanker@gmail.com
704-458-8402
Skype: rbanker
gTalk: rbanker@gmail.com

**Comment by xxv** [comment]
Sync can be done in a single step - the separation was to allow background upload/download while the main UI remained responsive.

Another option would be to investigate multi-threaded sync (same code running in different threads), but that's a much hairer issue and should be taken carefully.

**Comment by asterite** [comment]
My point is, until the sync is done in a single step, there isn't much I can do to improve the unsynced casts screen... or, put in another way, if I do something now, it'll become obsolete when the sync is done in a single step.

**Comment by xxv** [comment]
I've been meaning to investigate the need for a "dirty" bit to help indicate which things need to be sync'd, though this only applies for things which are known-changed on the client. There's no mechanism for getting a list of changes on the server side in a useful way (I'm open to any suggestions).

**Comment by xxv** [comment]
Ary: Yeah. I wasn't expecting this to be done before sync is fixed. This is actually a ticket to fix sync, not the UI.
