### ISSUE TITLE
CastEdit: gave up on finding location 

### ISSUE THREAD

**Issue by xxv** [UNICEF-Youth-Section/Locast-Android#26]
The location discovery code gave up too quickly. I was standing outdoors without a GPS fix.I hit the photo add button, took a photo and returned to the CastEdit activity. The location finding had stopped (evidenced by the system GPS icon going away) even though the text in the cast edit activity claimed it was still finding  it never added a location.

**Comment by rbanker** [comment]
Ary: can you take a look at this?

**Comment by asterite** [comment]
Yes

**Comment by asterite** [comment]
I'm not being able to reproduce this... How did you get to the CastEdit activity in the first place? I enter it clicking an itinerary in the itinerary list.

**Comment by rbanker** [comment]
Steve -- do you have any repro steps?

On Tue, Jan 24, 2012 at 3:11 PM, Ary Borenszweig <
reply@reply.github.com

> wrote:
> 
> I'm not being able to reproduce this... How did you get to the CastEdit
> activity in the first place? I enter it clicking an itinerary in the
> itinerary list.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/UNICEF-Youth-Section/Locast-Android/issues/26#issuecomment-3639446

## 

Rob Banker
rbanker@gmail.com
704-458-8402
Skype: rbanker
gTalk: rbanker@gmail.com

**Comment by xxv** [comment]
Yeah, The usual way - by clicking on an itinerary.

I think it may have to do with the activity stopping/restarting. I may have rotated the device in anticipation of taking the photo, so the CastEdit activity restarted before loading the camera app. Perhaps it's not preserving the location listening between restarts?

**Comment by xxv** [comment]
If the rotation doesn't trigger the desired behavior, I can go outside and test it again. I'll happily do field tests today :-)

**Comment by asterite** [comment]
I'll try rotating the device...

**Comment by asterite** [comment]
I think I fixed it... I really don't know, because the problem was around a line commented by "XXX hack", so I guess I just added another hack... By it would be nice to know what was the first hack for.

**Comment by xxv** [comment]
The first hack was documented! ;-)

I think the first hack was to prevent reloading of the content, by way of a change notification, while the cast media were loading into the cast. I think it went like this:
1. Cast loads
2. 1st cast media loads from network
3. cast reloads
4. 2nd cast media loads
5. cast reloads
6. 3rd cast media loads...

The issue there was when it was displaying the location, it would recenter the map, preventing the user from panning. The hack was there to just cause it to load once.
