### ISSUE TITLE
Testing AppUpdateChecker

### ISSUE THREAD

**Issue by rbanker** [UNICEF-Youth-Section/Locast-Android#28]
Steve:

I'd like to test this today. Is there an easy way for me to upload the new JSON file and .apk (FTP?), or should I just send them to you for updates?

http://locast.mit.edu/m/unicef_gis.json

What version number should we assign to this release?  It's currently got a version code of 26 and Version name of '2.1 UNICEF'.  Thinking we bump it to 2.5 UNICEF.

When we deploy tonight and notify stakeholder via email, I'll just give the 'downloadUrl' from the JSON file.

Thoughts?

RB

**Comment by xxv** [comment]
It'll be easiest to just email me the updated file.
