### ISSUE TITLE
Crash on Acquiring Location

### ISSUE THREAD

**Issue by rbanker** [UNICEF-Youth-Section/Locast-Android#3]
When running on device, Location acquisition crashs Activity.  It appears to happen after an indeterminate amount of time when the device can' establish the location (I was indoors).  After moving to an open area and location was established, app did not crash.

01-13 08:29:50.912: E/AndroidRuntime(2259): Caused by: java.lang.NullPointerException
01-13 08:29:50.912: E/AndroidRuntime(2259):     at edu.mit.mobile.android.locast.ver2.casts.CastEdit.setLocation(CastEdit.java:775)
01-13 08:29:50.912: E/AndroidRuntime(2259):     at edu.mit.mobile.android.locast.ver2.casts.CastEdit.processIntents(CastEdit.java:190)
01-13 08:29:50.912: E/AndroidRuntime(2259):     at edu.mit.mobile.android.locast.ver2.casts.CastEdit.onCreate(CastEdit.java:173)
01-13 08:29:50.912: E/AndroidRuntime(2259):     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1047)
01-13 08:29:50.912: E/AndroidRuntime(2259):     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2627)

**Comment by asterite** [comment]
Fixed in #b9f21a9533

**Comment by rbanker** [comment]
Rockin'!

Sent from my iPhone

On Jan 13, 2012, at 9:33 AM, Ary Borenszweig
reply@reply.github.com
wrote:
