### ISSUE TITLE
Sync Issues

### ISSUE THREAD

**Issue by rbanker** [UNICEF-Youth-Section/Locast-Android#31]
- Some complete casts are not uploading, even clicking synchronize on the admin app.
- One cast gave a “synchronization error,” but did not return to the previous list. 
- At least one cast uploaded to the admin site with GPS markings, but no picture. 
- Some casts are uploading unattached to a map, and thus not showing up on the website.
- I tried an offline test in an environment without GPS; I turned off wifi and took a picture.  I saw that the cast (title and picture) were saved in the admin app, but when I turned on the wifi to synchronize, the cast was uploaded to the site without the picture.
- Different phones show different numbers of casts in each map.  This may be because the numbers are not updating when we create a new cast, and are just looking at the current state when installed.

**Comment by xxv** [comment]
I think the not-uploading is due to the way that the MediaSync service works. Currently, media is enqueued to be sync'd only once (when the cast is uploaded). If anything happens during that sync, it will never be uploaded.

**Comment by xxv** [comment]
This should be fixed by 011fefb2447a2a4ccd266e17571252d45e8bebb1.
