### ISSUE TITLE
GPS Status after establishing location

### ISSUE THREAD

**Issue by rbanker** [UNICEF-Youth-Section/Locast-Android#4]
This is more of a thought than a bug...  I noticed that after the location is found, the GPS stays active and keeps updating.  Two lines of thought here:

Keeping the GPS active allows the location calculation to improve until the cast is saved

however...

Keeping the GPS active is a significant battery drain.

Do we:

1) Leave as is?
2) shut down the GPS after we've established the lock?
3) Shut down the GPS after n seconds after the lock?

**Comment by xxv** [comment]
Sounds like a bug to me.

I vote for option 2 or 3, perhaps based on accuracy instead of time. Maybe there could be a simple heuristic that looks at the rate of change of the accuracy and stops trying after it's plateau'd for n seconds.

**Comment by asterite** [comment]
You can ask the location provider to notify changes based on an interval of time and distance moved. So maybe setting the minium time to 10 seconds or 15 seconds would be enough.

**Comment by asterite** [comment]
About this, I think the use case is:
1. A user is walking
2. Sees something worthy to take a picture.
3. Opens the app, takes a picture, notes the details, saves.
4. Keeps walking until he finds something else...

Note that only during point 3 the GPS will be enabled, so I don't think it's bad to keep it open all that time... though it can be further optimized, I think for now it's good enough.

**Comment by rbanker** [comment]
This appears to be working fine now.
