### ISSUE TITLE
new location finder uses hard-coded provider names

### ISSUE THREAD

**Issue by xxv** [UNICEF-Youth-Section/Locast-Android#5]
The new location finder in CastEdit uses hard-coded LocationManager.GPS_PROVIDER and such. This will cause the app to crash on devices that don't have the given provider. Instead, the providers should be discovered using location criteria. If we want to ensure that there's GPS, we can do that by checking that it's there, but we shouldn't just assume it is.

**Comment by asterite** [comment]
I think the precision needed by the app needs to be GPS precision. If the GPS is not available, the app is useless. I think it's ok to hardcode the GPS provider... right?

**Comment by xxv** [comment]
No, you can get similar precision from other providers. Also: hard-coding a requirement on something that is not guaranteed is usually a recipe for disaster. Especially if the GPS can be disabled or any other variety of reasons why it may not be available.

Also, it breaks in testing because I'm trying to use network location (I don't have a window in my office and I want to use an actual phone).

**Comment by asterite** [comment]
Ok, I changed it to use all enabled location providers.
