### ISSUE TITLE
Casts are being duplicated

### ISSUE THREAD

**Issue by rbanker** [UNICEF-Youth-Section/Locast-Android#6]
New casts are being uploaded/duplicated.  Fairly easy to reproduce simply by creating a new cast.

**Comment by xxv** [comment]
Just to clarify about reproducing it: 
1. Start the app with a fresh DB
2. login
3. click on map, press "add cast"
4. fill in cast details, hit "save"
5. let auto-sync take place

6 ... 
1. see duplicate cast? where?

**Comment by xxv** [comment]
Also: what revision?

**Comment by rbanker** [comment]
The duplicate casts show up on the website after another sync takes place and is synced back to the device.  It's happening on HEAD right now.

**Comment by xxv** [comment]
Ary seems to have found the issue in the upload code's error handing. If the sync is interrupted between uploading and committing to the local database (if there are any errors), then the mobile loses sync with the server state and thinks that the remote content didn't succeed (when, in fact, it did).

**Comment by xxv** [comment]
fixed by cba35e1e4915beeca376fa3da0615e690770e00e
